### ISSUE TITLE
grge

### ISSUE THREAD

**Issue by danielbascunan** [ServiceNow/devtraining-needit-london#94]

**Comment by bsweets** [comment]
Thanks for submitting this, but we do not accept pull requests against the ServiceNow training master repository. As detailed in the module Exercises, you should connect your Studio instance to your own forked copy of the repository and not the ServiceNow master repo. Your work has not been saved to the ServiceNow master repository.  

These videos on the ServiceNow Developers YouTube channel explain how to configure to point to your forked copy of the repository and to troubleshoot setup issues:
https://www.youtube.com/playlist?list=PL3rNcyAiDYK32S3PiD5v4Esv5OcqdRZx1
